/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_maksimbulva_chess_chesslib_ChesslibWrapper */

#ifndef _Included_ru_maksimbulva_chess_chesslib_ChesslibWrapper
#define _Included_ru_maksimbulva_chess_chesslib_ChesslibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_maksimbulva_chess_chesslib_ChesslibWrapper
 * Method:    calculateLegalMovesCount
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ru_maksimbulva_chess_chesslib_ChesslibWrapper_calculateLegalMovesCount
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
