/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_maksimbulva_chess_chesslib_AbsChesslibWrapper */

#ifndef _Included_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
#define _Included_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    calculateLegalMovesCount
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_calculateLegalMovesCount
        (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    resetGame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_resetGame__J
        (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    resetGame
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_resetGame__Ljava_lang_String_2J
        (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    getCurrentPositionFen
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_getCurrentPositionFen
        (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    playMove
 * Signature: (Ljava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_playMove
        (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    findBestVariation
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_findBestVariation
        (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    createEngineInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_createEngineInstance
        (JNIEnv *, jobject);

/*
 * Class:     ru_maksimbulva_chess_chesslib_AbsChesslibWrapper
 * Method:    releaseEngineInstance
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_maksimbulva_chess_chesslib_AbsChesslibWrapper_releaseEngineInstance
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
